name: build

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0

      - name: Setup Java
        uses: actions/setup-java@v2.5.0
        with:
          distribution: adopt
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew projects clean build jacocoTestReport --no-daemon --refresh-dependencies

      - name: Upload coverage to Codecov
        if: matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v2.1.0
        with:
          flags: unittests
          fail_ci_if_error: true


  integration-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0

      - name: Setup Java
        uses: actions/setup-java@v2.5.0
        with:
          distribution: adopt
          java-version: 17

      - name: Setup HandBrake
        if: matrix.os == 'ubuntu-latest'
        run: sudo add-apt-repository ppa:stebbins/handbrake-releases && sudo apt-get update && sudo apt-get install handbrake-cli

      - name: Setup HandBrake
        if: matrix.os == 'windows-latest'
        run: choco install handbrake-cli

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Integration Test
        if: matrix.os == 'ubuntu-latest'
        # Linux needs sudo so Java process can access /usr/bin/HandBrakeCLI
        run: sudo ./gradlew projects clean integrationTest jacocoTestReport --no-daemon --refresh-dependencies

      - name: Integration Test
        if: matrix.os == 'windows-latest'
        run: ./gradlew projects clean integrationTest jacocoTestReport --no-daemon --refresh-dependencies

      - name: Upload coverage to Codecov
        if: matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v2.1.0
        with:
          flags: integrationtests
          fail_ci_if_error: true
