name: build
run-name: build by @${{ github.actor }}

on:
  pull_request:
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21

      - name: Build and test
        run: |
          chmod +x gradlew
          ./gradlew projects clean build integrationTest --no-daemon --refresh-dependencies

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.4
        with:
          flags: unit-tests
          fail_ci_if_error: true

  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21

      - name: Setup HandBrake
        run: sudo apt install handbrake-cli

      # Need to generate encoded files for the integration tests on the GitHub Actions agent.
      # Can't simply use the ones stored in git.
      # Guessing different hardware, OS, etc. results in slightly different output.
      - name: Generate test data
        run: |
          HandBrakeCLI --preset "Production Standard" -i auto-handbrake-cfr/src/integrationTest/resources/Big_Buck_Bunny_360_10s_1MB.mp4 -o auto-handbrake-cfr/src/integrationTest/resources/Big_Buck_Bunny_360_10s_1MB.cfr.mp4
          HandBrakeCLI --preset "Production Standard" -i auto-handbrake-cfr/src/integrationTest/resources/Big_Buck_Bunny_360_10s_2MB.mp4 -o auto-handbrake-cfr/src/integrationTest/resources/Big_Buck_Bunny_360_10s_2MB.cfr.mp4

      - name: Integration test
        # use retry cause the integration tests can be flaky. E.g. HandBrake crashing on the agent.
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 10
          command: |
            chmod +x gradlew
            ./gradlew projects clean integrationTest --no-daemon --refresh-dependencies

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.4
        with:
          flags: integration-tests
          fail_ci_if_error: true

  release:
    needs: [ build, integration-test ]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 21

      - name: Bump version
        id: version
        uses: paulhatch/semantic-version@v5.3.0

      - name: Build base image
        run: docker build -t handbrake-java-base -f base.Dockerfile .

      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker images
        run: ./gradlew jib -Djib.to.tags=${{ steps.version.outputs.version }}

      - name: Create GitHub tag and release
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: ${{ steps.version.outputs.version_tag }}
          generate_release_notes: true