name: build

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0

      - name: Setup Java
        uses: actions/setup-java@v2.5.0
        with:
          distribution: adopt
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew projects clean build jacocoTestReport --no-daemon --refresh-dependencies

      - name: Upload coverage to Codecov (Windows only)
        if: matrix.os == 'windows-latest'
        uses: codecov/codecov-action@v2.1.0
        with:
          flags: unittests
          fail_ci_if_error: true
