name: dependency-submission
run-name: dependency-submission by @${{ github.actor }}

on:
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: false

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4
        with:
          dependency-graph: 'generate-and-submit'
