name: docker

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  packages: write

jobs:
  docker:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java 19
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 19

      - name: Bump version
        id: version
        uses: paulhatch/semantic-version@v5.0.2

      - name: Build base image
        run: docker build -t handbrake-java-base -f base.Dockerfile .

      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker images
        run: ./gradlew jib -Djib.to.tags=${{ steps.version.outputs.version }}

      - name: Create GitHub tag and release
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: ${{ steps.version.outputs.version_tag }}
          generate_release_notes: true