name: docker

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.1.0

      - name: Build Dockerfile
        run: docker build -t handbrake .
