name: docker

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0

      - name: Setup Java 17
        uses: actions/setup-java@v3.6.0
        with:
          distribution: adopt
          java-version: 17

      - name: Build base image
        run: docker build -t handbrake-java-base .

      - name: Run Jib
        run: ./gradlew jibDockerBuild
