name: docker

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0

      - name: Build base image
        run: docker build -t handbrake-java-base .

      - name: Build auto-handbrake-cfr image
        run: ./gradlew :auto-handbrake-cfr:jibDockerBuild
