name: integration-test

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  integration-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0

      - name: Setup Java 19
        uses: actions/setup-java@v3.8.0
        with:
          distribution: adopt
          java-version: 19

      - name: Setup HandBrake (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt install handbrake-cli

      - name: Setup HandBrake (Windows)
        if: matrix.os == 'windows-latest'
        run: choco install handbrake-cli

      - name: Setup HandBrake (Mac)
        if: matrix.os == 'macos-latest'
        run: brew install handbrake

      # Need to generate encoded files for the integration tests on the GitHub Actions agent.
      # Can't simply use the ones stored in git, guessing different hardware, OS, etc. results in
      # slightly different output.
      - name: Generate test data
        run: |
          HandBrakeCLI --preset "Production Standard" -i auto-handbrake-cfr/src/integrationTest/resources/Big_Buck_Bunny_360_10s_1MB.mp4 -o auto-handbrake-cfr/src/integrationTest/resources/Big_Buck_Bunny_360_10s_1MB.cfr.mp4
          HandBrakeCLI --preset "Production Standard" -i auto-handbrake-cfr/src/integrationTest/resources/Big_Buck_Bunny_360_10s_2MB.mp4 -o auto-handbrake-cfr/src/integrationTest/resources/Big_Buck_Bunny_360_10s_2MB.cfr.mp4

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Integration Test
        # use retry cause the integration tests can be flaky. E.g. HandBrake crashing on the agent.
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 10
          command: ./gradlew projects clean integrationTest --no-daemon --refresh-dependencies

      - name: Upload coverage to Codecov (Linux only)
        if: matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v2.1.0
        with:
          flags: integration-tests
          fail_ci_if_error: true
