name: integration-test

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0

      - name: Setup Java
        uses: actions/setup-java@v2.5.0
        with:
          distribution: adopt
          java-version: 17

      - name: Setup HandBrake
        run: add-apt-repository ppa:stebbins/handbrake-releases && apt-get update && apt-get install handbrake-cli

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Integration Test
        run: ./gradlew projects clean integrationTest jacocoTestReport --no-daemon --refresh-dependencies

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          flags: integrationtests
          fail_ci_if_error: true
