name: integration-test

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  integration-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # TODO linux build not working, see below
#        os: [ windows-latest, macos-latest ]
        os: [ ubuntu-latest ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0

#      - name: Setup Java
#        uses: actions/setup-java@v2.5.0
#        with:
#          distribution: adopt
#          java-version: 17
      - name: Setup Java (sudo)
        run: |
          wget -O- https://apt.corretto.aws/corretto.key | sudo apt-key add - \
          && sudo add-apt-repository 'deb https://apt.corretto.aws stable main' \
          && sudo apt-get update; sudo apt-get install -y java-17-amazon-corretto-jdk

      - name: Setup HandBrake (Windows)
        if: matrix.os == 'windows-latest'
        run: choco install handbrake-cli

      - name: Setup HandBrake (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo add-apt-repository ppa:stebbins/handbrake-releases && sudo apt-get update && sudo apt-get install handbrake-cli

      - name: Setup HandBrake (Mac)
        if: matrix.os == 'macos-latest'
        run: brew install handbrake

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Integration Test
        run: sudo ./gradlew projects clean integrationTest jacocoTestReport --no-daemon --refresh-dependencies

      # TODO this needs fixing too...
#      - name: Upload coverage to Codecov (Windows only)
#        if: matrix.os == 'windows-latest'
#        uses: codecov/codecov-action@v2.1.0
#        with:
#          flags: integrationtests
#          fail_ci_if_error: true
