name: integration-test

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  integration-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0

      - name: Setup Java
        uses: actions/setup-java@v2.5.0
        with:
          distribution: adopt
          java-version: 17

      - name: Setup HandBrake (Windows)
        if: matrix.os == 'windows-latest'
        run: choco install handbrake-cli

      - name: Setup HandBrake (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo add-apt-repository ppa:stebbins/handbrake-releases && apt-get update && apt-get install handbrake-cli

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Integration Test (Windows)
        if: matrix.os == 'windows-latest'
        run: ./gradlew projects clean integrationTest jacocoTestReport --no-daemon --refresh-dependencies

      - name: Integration Test (Linux)
        if: matrix.os == 'ubuntu-latest'
        # Linux needs sudo so Java process can access /usr/bin/HandBrakeCLI TODO why it runs with Java 11?
        run: ./gradlew projects clean integrationTest jacocoTestReport --no-daemon --refresh-dependencies

      - name: Upload coverage to Codecov (Windows only)
        if: matrix.os == 'windows-latest'
        uses: codecov/codecov-action@v2.1.0
        with:
          flags: integrationtests
          fail_ci_if_error: true
